republishers:
# - topic: "/map_metadata"
#   latched: true
#   msg_type: "nav_msgs/msg/MapMetaData"
#   mappings:
#   - field: "resolution"
#     mapping_type: "single_field"
#     out:
#       topic: "/inorbit/map_res_test"
#       key: "map_resolution"

- topic: "/current_states"
  qos: 5
  qos_reliability: 2  # reliable
  qos_durability: 2   # transient_local
  msg_type: "quasi_msgs/msg/CurrentState"
  mappings:
  - mapping_type: "single_field"
    field: "wheel_power"
    out:
      topic: "/inorbit/custom_data"
      key: "wheels_power"

- topic: "/battery_state"
  qos: 5
  qos_reliability: 2  # best_effort
  qos_durability: 2   # volatile
  msg_type: "sensor_msgs/msg/BatteryState"
  mappings:
  - mapping_type: "json_of_fields"
    field: ""  # empty field means the whole message
    mapping_options:
      fields: ["voltage", "charge", "percentage", "current", "temperature", "power_supply_status", "power_supply_health", "capacity"]
    out:
      topic: "/inorbit/custom_data"
      key: "battery_state"

- topic: "/cart_manager/waypoints"
  qos: 5
  qos_reliability: 1  # reliable
  qos_durability: 1   # transient_local
  msg_type: "quasi_cart_msgs/msg/Waypoints"
  mappings:
  - field: "waypoints"
    mapping_type: "array_of_fields"
    mapping_options:
      fields: ["index", "name"]
    out:
      topic: "/inorbit/custom_data"
      key: "waypoints"

- topic: "/cloud_connect/routes_updated"
  qos: 5
  qos_reliability: 1  # reliable
  qos_durability: 1   # transient_local
  msg_type: "quasi_cart_msgs/msg/Routes"
  mappings:
  - field: "routes"
    mapping_type: "array_of_fields"
    mapping_options:
      fields: ["id", "name", "waypoints_count"]
    out:
      topic: "/inorbit/custom_data"
      key: "routes"

- topic: "/cart_manager/navigation_result"
  qos: 5
  qos_reliability: 1  # reliable
  qos_durability: 2   # volatile
  msg_type: "quasi_cart_msgs/msg/NavigationResult"
  mappings:
  - mapping_type: "json_of_fields"
    field: ""  # empty field means the whole message
    mapping_options:
      fields: ["waypoint_name", "result_code", "error_code", "error_msg", "navigation_duration", "end_time", "distance", "route"]
    out:
      topic: "/inorbit/custom_data"
      key: "navigation_result"

